/* ═════════════════════════════════════════════════════════════
   EXT-DATA.JS — данные для новых разделов:
   IRREGULAR_VERBS / REGULAR_VERBS / LISTENING / SPEAKING
   ═════════════════════════════════════════════════════════════ */

// ---------- НЕПРАВИЛЬНЫЕ ГЛАГОЛЫ (по уровням) ----------
const IRREGULAR_VERBS = [
  {base:"be",past:"was/were",part:"been",ru:"быть",level:"A1"},
  {base:"go",past:"went",part:"gone",ru:"идти",level:"A1"},
  {base:"have",past:"had",part:"had",ru:"иметь",level:"A1"},
  {base:"do",past:"did",part:"done",ru:"делать",level:"A1"},
  {base:"see",past:"saw",part:"seen",ru:"видеть",level:"A1"},
  {base:"get",past:"got",part:"got/gotten",ru:"получать",level:"A1"},
  {base:"make",past:"made",part:"made",ru:"делать/создавать",level:"A1"},
  {base:"say",past:"said",part:"said",ru:"говорить/сказать",level:"A1"},
  {base:"eat",past:"ate",part:"eaten",ru:"есть (кушать)",level:"A1"},
  {base:"drink",past:"drank",part:"drunk",ru:"пить",level:"A1"},
  {base:"come",past:"came",part:"come",ru:"приходить",level:"A1"},
  {base:"take",past:"took",part:"taken",ru:"брать",level:"A1"},
  {base:"give",past:"gave",part:"given",ru:"давать",level:"A1"},
  {base:"know",past:"knew",part:"known",ru:"знать",level:"A1"},
  {base:"think",past:"thought",part:"thought",ru:"думать",level:"A1"},
  {base:"see",past:"saw",part:"seen",ru:"видеть",level:"A1"},
  {base:"read",past:"read",part:"read",ru:"читать",level:"A1"},
  {base:"write",past:"wrote",part:"written",ru:"писать",level:"A1"},
  {base:"run",past:"ran",part:"run",ru:"бежать",level:"A1"},
  {base:"sit",past:"sat",part:"sat",ru:"сидеть",level:"A1"},

  {base:"buy",past:"bought",part:"bought",ru:"покупать",level:"A2"},
  {base:"bring",past:"brought",part:"brought",ru:"приносить",level:"A2"},
  {base:"catch",past:"caught",part:"caught",ru:"ловить",level:"A2"},
  {base:"choose",past:"chose",part:"chosen",ru:"выбирать",level:"A2"},
  {base:"drive",past:"drove",part:"driven",ru:"водить машину",level:"A2"},
  {base:"fall",past:"fell",part:"fallen",ru:"падать",level:"A2"},
  {base:"feel",past:"felt",part:"felt",ru:"чувствовать",level:"A2"},
  {base:"find",past:"found",part:"found",ru:"находить",level:"A2"},
  {base:"fly",past:"flew",part:"flown",ru:"летать",level:"A2"},
  {base:"forget",past:"forgot",part:"forgotten",ru:"забывать",level:"A2"},
  {base:"hear",past:"heard",part:"heard",ru:"слышать",level:"A2"},
  {base:"keep",past:"kept",part:"kept",ru:"хранить/держать",level:"A2"},
  {base:"leave",past:"left",part:"left",ru:"покидать/уходить",level:"A2"},
  {base:"lose",past:"lost",part:"lost",ru:"терять",level:"A2"},
  {base:"meet",past:"met",part:"met",ru:"встречать",level:"A2"},
  {base:"pay",past:"paid",part:"paid",ru:"платить",level:"A2"},
  {base:"put",past:"put",part:"put",ru:"класть",level:"A2"},
  {base:"sell",past:"sold",part:"sold",ru:"продавать",level:"A2"},
  {base:"send",past:"sent",part:"sent",ru:"отправлять",level:"A2"},
  {base:"sleep",past:"slept",part:"slept",ru:"спать",level:"A2"},

  {base:"speak",past:"spoke",part:"spoken",ru:"говорить",level:"B1"},
  {base:"stand",past:"stood",part:"stood",ru:"стоять",level:"B1"},
  {base:"swim",past:"swam",part:"swum",ru:"плавать",level:"B1"},
  {base:"teach",past:"taught",part:"taught",ru:"учить (преподавать)",level:"B1"},
  {base:"tell",past:"told",part:"told",ru:"рассказывать",level:"B1"},
  {base:"understand",past:"understood",part:"understood",ru:"понимать",level:"B1"},
  {base:"wear",past:"wore",part:"worn",ru:"носить (одежду)",level:"B1"},
  {base:"win",past:"won",part:"won",ru:"выигрывать",level:"B1"},
  {base:"break",past:"broke",part:"broken",ru:"ломать",level:"B1"},
  {base:"build",past:"built",part:"built",ru:"строить",level:"B1"},
  {base:"begin",past:"began",part:"begun",ru:"начинать",level:"B1"},
  {base:"draw",past:"drew",part:"drawn",ru:"рисовать",level:"B1"},
  {base:"grow",past:"grew",part:"grown",ru:"расти",level:"B1"},
  {base:"hold",past:"held",part:"held",ru:"держать",level:"B1"},
  {base:"hide",past:"hid",part:"hidden",ru:"прятать",level:"B1"},

  {base:"arise",past:"arose",part:"arisen",ru:"возникать",level:"B2"},
  {base:"bear",past:"bore",part:"borne",ru:"нести/выносить",level:"B2"},
  {base:"bend",past:"bent",part:"bent",ru:"сгибать",level:"B2"},
  {base:"bind",past:"bound",part:"bound",ru:"связывать",level:"B2"},
  {base:"bite",past:"bit",part:"bitten",ru:"кусать",level:"B2"},
  {base:"bleed",past:"bled",part:"bled",ru:"кровоточить",level:"B2"},
  {base:"burst",past:"burst",part:"burst",ru:"лопаться",level:"B2"},
  {base:"cast",past:"cast",part:"cast",ru:"бросать/отливать",level:"B2"},
  {base:"cling",past:"clung",part:"clung",ru:"цепляться",level:"B2"},
  {base:"creep",past:"crept",part:"crept",ru:"ползти",level:"B2"},
  {base:"deal",past:"dealt",part:"dealt",ru:"иметь дело/торговать",level:"B2"},
  {base:"dig",past:"dug",part:"dug",ru:"копать",level:"B2"},
  {base:"feed",past:"fed",part:"fed",ru:"кормить",level:"B2"},
  {base:"fight",past:"fought",part:"fought",ru:"драться/бороться",level:"B2"},
  {base:"freeze",past:"froze",part:"frozen",ru:"замерзать",level:"B2"},

  {base:"forgive",past:"forgave",part:"forgiven",ru:"прощать",level:"C1"},
  {base:"forsake",past:"forsook",part:"forsaken",ru:"покидать/отрекаться",level:"C1"},
  {base:"grind",past:"ground",part:"ground",ru:"молоть/шлифовать",level:"C1"},
  {base:"lay",past:"laid",part:"laid",ru:"класть/укладывать",level:"C1"},
  {base:"lead",past:"led",part:"led",ru:"вести/руководить",level:"C1"},
  {base:"lean",past:"leant/leaned",part:"leant/leaned",ru:"наклоняться",level:"C1"},
  {base:"leap",past:"leapt/leaped",part:"leapt/leaped",ru:"прыгать",level:"C1"},
  {base:"mistake",past:"mistook",part:"mistaken",ru:"ошибаться",level:"C1"},
  {base:"overcome",past:"overcame",part:"overcome",ru:"преодолевать",level:"C1"},
  {base:"seek",past:"sought",part:"sought",ru:"искать",level:"C1"},
  {base:"shrink",past:"shrank",part:"shrunk",ru:"сжиматься",level:"C1"},
  {base:"spin",past:"spun",part:"spun",ru:"вращать(ся)",level:"C1"},
  {base:"spring",past:"sprang",part:"sprung",ru:"вскакивать",level:"C1"},
  {base:"strive",past:"strove",part:"striven",ru:"стремиться",level:"C1"},
  {base:"swear",past:"swore",part:"sworn",ru:"клясться/ругаться",level:"C1"},

  {base:"awake",past:"awoke",part:"awoken",ru:"пробуждаться",level:"C2"},
  {base:"beget",past:"begot",part:"begotten",ru:"порождать",level:"C2"},
  {base:"behold",past:"beheld",part:"beheld",ru:"узреть (высок.)",level:"C2"},
  {base:"cleave",past:"cleft/clove",part:"cleft/cloven",ru:"раскалывать",level:"C2"},
  {base:"dwell",past:"dwelt",part:"dwelt",ru:"обитать/пребывать",level:"C2"},
  {base:"forbid",past:"forbade",part:"forbidden",ru:"запрещать",level:"C2"},
  {base:"rend",past:"rent",part:"rent",ru:"разрывать (высок.)",level:"C2"},
  {base:"rid",past:"rid",part:"rid",ru:"избавлять",level:"C2"},
  {base:"shear",past:"sheared",part:"shorn",ru:"стричь (овец)",level:"C2"},
  {base:"slay",past:"slew",part:"slain",ru:"убивать (высок.)",level:"C2"},
  {base:"smite",past:"smote",part:"smitten",ru:"поражать (высок.)",level:"C2"},
  {base:"sow",past:"sowed",part:"sown",ru:"сеять",level:"C2"},
  {base:"strew",past:"strewed",part:"strewn",ru:"усыпать",level:"C2"},
  {base:"thrive",past:"throve/thrived",part:"thriven/thrived",ru:"процветать",level:"C2"},
  {base:"wring",past:"wrung",part:"wrung",ru:"выжимать/скручивать",level:"C2"},
];

// ---------- ПРАВИЛЬНЫЕ ГЛАГОЛЫ (по уровням, форма -ed) ----------
const REGULAR_VERBS = [
  {base:"work",past:"worked",part:"worked",ru:"работать",level:"A1"},
  {base:"play",past:"played",part:"played",ru:"играть",level:"A1"},
  {base:"live",past:"lived",part:"lived",ru:"жить",level:"A1"},
  {base:"like",past:"liked",part:"liked",ru:"нравиться",level:"A1"},
  {base:"want",past:"wanted",part:"wanted",ru:"хотеть",level:"A1"},
  {base:"help",past:"helped",part:"helped",ru:"помогать",level:"A1"},
  {base:"walk",past:"walked",part:"walked",ru:"гулять/ходить",level:"A1"},
  {base:"talk",past:"talked",part:"talked",ru:"разговаривать",level:"A1"},
  {base:"watch",past:"watched",part:"watched",ru:"смотреть",level:"A1"},
  {base:"listen",past:"listened",part:"listened",ru:"слушать",level:"A1"},
  {base:"clean",past:"cleaned",part:"cleaned",ru:"убирать/чистить",level:"A2"},
  {base:"cook",past:"cooked",part:"cooked",ru:"готовить",level:"A2"},
  {base:"finish",past:"finished",part:"finished",ru:"заканчивать",level:"A2"},
  {base:"open",past:"opened",part:"opened",ru:"открывать",level:"A2"},
  {base:"close",past:"closed",part:"closed",ru:"закрывать",level:"A2"},
  {base:"travel",past:"travelled",part:"travelled",ru:"путешествовать",level:"A2"},
  {base:"study",past:"studied",part:"studied",ru:"учиться/изучать",level:"A2"},
  {base:"carry",past:"carried",part:"carried",ru:"нести",level:"A2"},
  {base:"try",past:"tried",part:"tried",ru:"пытаться",level:"A2"},
  {base:"stop",past:"stopped",part:"stopped",ru:"останавливаться",level:"A2"},
  {base:"plan",past:"planned",part:"planned",ru:"планировать",level:"B1"},
  {base:"prepare",past:"prepared",part:"prepared",ru:"готовиться",level:"B1"},
  {base:"discuss",past:"discussed",part:"discussed",ru:"обсуждать",level:"B1"},
  {base:"decide",past:"decided",part:"decided",ru:"решать",level:"B1"},
  {base:"explain",past:"explained",part:"explained",ru:"объяснять",level:"B1"},
  {base:"improve",past:"improved",part:"improved",ru:"улучшать",level:"B1"},
  {base:"introduce",past:"introduced",part:"introduced",ru:"представлять(ся)",level:"B1"},
  {base:"organize",past:"organized",part:"organized",ru:"организовывать",level:"B1"},
  {base:"suggest",past:"suggested",part:"suggested",ru:"предлагать",level:"B1"},
  {base:"remember",past:"remembered",part:"remembered",ru:"вспоминать",level:"B1"},
  {base:"achieve",past:"achieved",part:"achieved",ru:"достигать",level:"B2"},
  {base:"analyze",past:"analyzed",part:"analyzed",ru:"анализировать",level:"B2"},
  {base:"argue",past:"argued",part:"argued",ru:"спорить/утверждать",level:"B2"},
  {base:"establish",past:"established",part:"established",ru:"учреждать",level:"B2"},
  {base:"determine",past:"determined",part:"determined",ru:"определять",level:"B2"},
  {base:"emphasize",past:"emphasized",part:"emphasized",ru:"подчёркивать",level:"B2"},
  {base:"influence",past:"influenced",part:"influenced",ru:"влиять",level:"B2"},
  {base:"negotiate",past:"negotiated",part:"negotiated",ru:"вести переговоры",level:"B2"},
  {base:"predict",past:"predicted",part:"predicted",ru:"предсказывать",level:"B2"},
  {base:"summarize",past:"summarized",part:"summarized",ru:"обобщать",level:"B2"},
  {base:"acknowledge",past:"acknowledged",part:"acknowledged",ru:"признавать",level:"C1"},
  {base:"advocate",past:"advocated",part:"advocated",ru:"выступать за",level:"C1"},
  {base:"contemplate",past:"contemplated",part:"contemplated",ru:"размышлять",level:"C1"},
  {base:"differentiate",past:"differentiated",part:"differentiated",ru:"различать",level:"C1"},
  {base:"undermine",past:"undermined",part:"undermined",ru:"подрывать",level:"C1"},
  {base:"reinforce",past:"reinforced",part:"reinforced",ru:"усиливать",level:"C1"},
  {base:"substantiate",past:"substantiated",part:"substantiated",ru:"обосновывать",level:"C2"},
  {base:"corroborate",past:"corroborated",part:"corroborated",ru:"подтверждать",level:"C2"},
  {base:"perpetuate",past:"perpetuated",part:"perpetuated",ru:"увековечивать",level:"C2"},
  {base:"reconcile",past:"reconciled",part:"reconciled",ru:"примирять",level:"C2"},
];

// ---------- LISTENING: Task 5 (5 заданий) для каждого уровня ----------
const LISTENING = {
  A1: {
    title: "My Family",
    text: "Hi! My name is Anna. I am ten years old. This is my family. My mother is a teacher. My father is a doctor. I have one brother. His name is Tom. We live in a small house. I like my family very much.",
    tasks: [
      {q:"How old is Anna?", options:["Ten","Eleven","Nine","Twelve"], a:0},
      {q:"What is her mother's job?", options:["Doctor","Teacher","Cook","Driver"], a:1},
      {q:"What is her father's job?", options:["Teacher","Driver","Doctor","Engineer"], a:2},
      {q:"What is her brother's name?", options:["Tim","Tom","Sam","Jack"], a:1},
      {q:"Where do they live?", options:["A big flat","A small house","A hotel","A village"], a:1},
    ]
  },
  A2: {
    title: "A Trip to the City",
    text: "Last weekend I went to the city with my friends. We visited a museum and had lunch in a small cafe. After that, we walked in the park and took photos. In the evening, we went home by bus because it started to rain.",
    tasks: [
      {q:"When did the trip happen?", options:["Last weekend","Yesterday","This morning","Last year"], a:0},
      {q:"Who did they visit?", options:["A zoo","A museum","A theatre","A castle"], a:1},
      {q:"Where did they have lunch?", options:["At home","In a cafe","In a park","At school"], a:1},
      {q:"What did they do after lunch?", options:["Slept","Shopped","Walked in the park","Watched a film"], a:2},
      {q:"How did they go home?", options:["By car","On foot","By bus","By train"], a:2},
    ]
  },
  B1: {
    title: "Choosing a Career",
    text: "Choosing a career is one of the most important decisions in life. Many young people are not sure what job suits them best. Experts suggest that you should think about your interests, your strengths and the way you like to work before making a final decision. It is also a good idea to talk to people who already work in the field you are interested in.",
    tasks: [
      {q:"What is the topic of the text?", options:["Studying abroad","Choosing a career","Making friends","Learning languages"], a:1},
      {q:"What are young people often unsure about?", options:["Where to live","Which job suits them","How to study","What to eat"], a:1},
      {q:"What should you think about first, according to experts?", options:["Your salary","Your interests and strengths","Your friends' opinion","Your age"], a:1},
      {q:"What extra advice is given?", options:["Read more books","Talk to people already in the field","Change jobs often","Study abroad"], a:1},
      {q:"How is this decision described?", options:["Unimportant","One of the most important","Easy","Quick"], a:1},
    ]
  },
  B2: {
    title: "The Impact of Social Media",
    text: "Social media has transformed the way people communicate and share information. While it allows people to stay connected across long distances, it has also raised concerns about privacy and mental health. Studies suggest that excessive use of social media can lead to feelings of anxiety and isolation, especially among teenagers. On the other hand, it can be a powerful tool for education and raising awareness about important issues.",
    tasks: [
      {q:"What has social media changed?", options:["The way people travel","The way people communicate","The way people cook","The way people sleep"], a:1},
      {q:"What concerns are mentioned?", options:["Cost and speed","Privacy and mental health","Design and colour","Weather and climate"], a:1},
      {q:"Who is especially affected by anxiety, according to the text?", options:["Elderly people","Teenagers","Teachers","Business owners"], a:1},
      {q:"What positive use of social media is mentioned?", options:["Selling products","Education and raising awareness","Playing games","Watching films"], a:1},
      {q:"What kind of feelings can excessive use cause?", options:["Joy and excitement","Anxiety and isolation","Confidence and calm","Curiosity and hope"], a:1},
    ]
  },
  C1: {
    title: "The Ethics of Artificial Intelligence",
    text: "As artificial intelligence systems become more capable, questions about their ethical use grow increasingly urgent. Developers must grapple with issues such as algorithmic bias, accountability and the potential displacement of human labour. Some argue that strict regulation is essential to prevent misuse, while others contend that overregulation could stifle innovation. Striking the right balance requires collaboration between technologists, policymakers and the public.",
    tasks: [
      {q:"What grows more urgent as AI becomes more capable?", options:["Its cost","Ethical questions","Its speed","Its size"], a:1},
      {q:"Which issue is NOT mentioned?", options:["Algorithmic bias","Accountability","Labour displacement","Battery life"], a:3},
      {q:"What do some people argue is essential?", options:["More funding","Strict regulation","Faster computers","Fewer developers"], a:1},
      {q:"What is the risk of overregulation, according to critics?", options:["It could stifle innovation","It could be too cheap","It could increase bias","It could speed up progress"], a:0},
      {q:"Who should collaborate to find balance?", options:["Only governments","Only companies","Technologists, policymakers and the public","Only universities"], a:2},
    ]
  },
  C2: {
    title: "The Paradox of Choice",
    text: "Contemporary consumer culture is predicated on the assumption that greater choice invariably leads to greater satisfaction. However, psychological research suggests the opposite may be true: an overabundance of options can induce decision paralysis and diminish overall contentment. This phenomenon, often termed the paradox of choice, illustrates how cognitive overload undermines rather than enhances our sense of agency and well-being.",
    tasks: [
      {q:"What assumption underlies consumer culture?", options:["Less choice is better","Greater choice leads to greater satisfaction","Price matters most","Brands are unimportant"], a:1},
      {q:"What does psychological research suggest?", options:["The assumption is fully correct","The opposite may be true","Choice has no effect","Only price matters"], a:1},
      {q:"What can too many options cause?", options:["Faster decisions","Decision paralysis","Higher income","Better memory"], a:1},
      {q:"What is this phenomenon called?", options:["The paradox of choice","The theory of relativity","The law of demand","The comfort effect"], a:0},
      {q:"What does cognitive overload do, according to the text?", options:["Enhances well-being","Undermines our sense of agency and well-being","Has no impact","Improves decision speed"], a:1},
    ]
  },
};

// ---------- SPEAKING: Task 3 (3 фразы) для каждого уровня ----------
const SPEAKING = {
  A1: [
    "My name is Anna.",
    "I like apples and bananas.",
    "This is my family.",
  ],
  A2: [
    "I went to the city last weekend.",
    "She works in a big office.",
    "We usually have dinner at seven o'clock.",
  ],
  B1: [
    "I think choosing a career is very important.",
    "He has been learning English for three years.",
    "If it rains tomorrow, we will stay at home.",
  ],
  B2: [
    "Social media has changed the way we communicate.",
    "Although it was raining, they decided to go for a walk.",
    "The report should have been finished by now.",
  ],
  C1: [
    "Developers must grapple with issues such as algorithmic bias and accountability.",
    "Striking the right balance requires collaboration between different groups.",
    "Had I known about the meeting, I would have attended it.",
  ],
  C2: [
    "The paradox of choice illustrates how cognitive overload undermines our well-being.",
    "Contemporary consumer culture is predicated on a questionable assumption.",
    "Notwithstanding the criticism, the proposal was ultimately approved.",
  ],
};